# Generated by Django 4.2.5 on 2023-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.CharField(default='linkREPLACE', max_length=500),
            preserve_default=False,
        ),
    ]
