# Generated by Django 4.2.5 on 2023-09-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/stories/'),
        ),
        migrations.AlterField(
            model_name='pageobject',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
