# Generated by Django 4.2.5 on 2023-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='Without description'),
        ),
    ]
