# Generated by Django 4.2.5 on 2023-09-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0002_alter_pageobject_photo_alter_pageobject_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/stories/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='page_objects',
            field=models.ManyToManyField(blank=True, to='lores.pageobject'),
        ),
    ]
