# Generated by Django 4.2.5 on 2023-09-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0003_alter_pageobject_photo_alter_story_page_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/stories/'),
        ),
    ]
