# Generated by Django 4.2.5 on 2023-09-25 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0004_alter_pageobject_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='page_objects',
        ),
        migrations.AddField(
            model_name='story',
            name='page_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
