# Generated by Django 4.2.5 on 2023-09-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0006_ability_category_cost_effect_itemclass_item_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(default='Without description', max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/units/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='name',
        ),
        migrations.AddField(
            model_name='ability',
            name='costs',
            field=models.ManyToManyField(to='lores.cost'),
        ),
        migrations.AddField(
            model_name='ability',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/abilities/'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AddField(
            model_name='effect',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/effects/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/heroes/'),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/items/'),
        ),
        migrations.AddField(
            model_name='itemclass',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/itemclasses/'),
        ),
        migrations.AddField(
            model_name='cost',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lores.unit'),
        ),
    ]
