# Generated by Django 4.2.5 on 2023-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0007_unit_remove_ability_cost_remove_cost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='items',
            field=models.ManyToManyField(blank=True, to='lores.item'),
        ),
    ]
