# Generated by Django 4.2.5 on 2023-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0008_hero_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='category',
        ),
        migrations.AddField(
            model_name='hero',
            name='category',
            field=models.ManyToManyField(blank=True, to='lores.category'),
        ),
    ]
