# Generated by Django 4.2.5 on 2023-09-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lores', '0009_remove_hero_category_hero_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='category',
            new_name='categories',
        ),
    ]
